name: snowlaps-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.9
  - numpy
  - pandas
  - tensorflow
  - pysolar
  - pytz
  - timezonefinder
  - scikit-learn
  - streamlit
  - plotly
  - pip
  - flake8
  - pytest
  - pytest-lazy-fixture
  - pylint
  - pre-commit
