name: snowlaps
channels:
  - conda-forge/label/cf202003
  - https://conda.software.inl.gov/public
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - tensorflow
  - pysolar
  - pytz
  - timezonefinder
  - scikit-learn
