[[pages]]
path = "../app/pages/introduction.py"
name = "Home"
icon = "🏠"

[[pages]]
path = "../app/pages/snowlaps_forward.py"
name = "Forward"
icon = ":arrow_right_hook:"

[[pages]]
path = "../app/pages/snowlaps_inversion.py"
name = "Inverse"
icon = ":leftwards_arrow_with_hook:"

[[pages]]
path = "../app/pages/get_help.py"
name = "Get support"
icon = ":woman-surfing:"
